# -*- coding: utf-8 -*-
"""Punto_4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tQVe9F1YLVecA22rpRxz6TIHp2dFbESh
"""

def mayor_suma_consecutiva(lista):
    if len(lista) < 2:
        return None
    mayor_suma = lista[0] + lista[1]
    for i in range(1, len(lista) - 1):
        suma_actual = lista[i] + lista[i + 1]
        if suma_actual > mayor_suma:
            mayor_suma = suma_actual
    return mayor_suma

numeros = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
resultado = mayor_suma_consecutiva(numeros)
print("La mayor suma entre dos elementos consecutivos en la lista es:", resultado)