# -*- coding: utf-8 -*-
"""Punto_1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LJkoPPLK800F-OxqKAgO66p9cTAQgzT2
"""

def operacion_basica(num1, num2, operador):
    if operador == "+":
        return num1 + num2
    elif operador == "-":
        return num1 - num2
    elif operador == "*":
        return num1 * num2
    elif operador == "/":
        if num2 != 0:
            return num1 / num2
        else:
            return "Error: división por cero"
    else:
        return "Operador no válido"

num1 = float(input("Ingrese el primer número: "))
num2 = float(input("Ingrese el segundo número: "))
operador = input("Ingrese el operador de la operación que desea (+, -, *, /): ")

resultado = operacion_basica(num1, num2, operador)
print("Resultado:", resultado)