# -*- coding: utf-8 -*-
"""Punto_5

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1416k1DUkmaz6Yvtpc2tzpV3RqyFQfTGi
"""

def mismos_caracteres(lista):
    resultado = []
    for palabra in lista:
        caracteres_unicos = set(palabra)
        if len(caracteres_unicos) == len(palabra):
            resultado.append(palabra)
    return resultado

lista_palabras = ["amor", "roma", "perro", "murciélago"]
resultado = mismos_caracteres(lista_palabras)
print("Elementos con los mismos caracteres:", resultado)